"""empty message

Revision ID: 12150291a0a2
Revises: 9fe16dd006ec
Create Date: 2021-05-30 17:21:36.846380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12150291a0a2'
down_revision = '9fe16dd006ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
