"""empty message

Revision ID: 7f123f517854
Revises: 3e1bc490b628
Create Date: 2021-06-12 15:30:25.821851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f123f517854'
down_revision = '3e1bc490b628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'created_date')
    op.drop_column('artists', 'created_date')
    # ### end Alembic commands ###
