"""empty message

Revision ID: c03bc85c3806
Revises: d30b071e4e17
Create Date: 2021-06-21 21:18:43.663321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03bc85c3806'
down_revision = 'd30b071e4e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'songs', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'artist_id')
    # ### end Alembic commands ###
