"""empty message

Revision ID: d30b071e4e17
Revises: 743fd811f33f
Create Date: 2021-06-21 21:03:19.411236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30b071e4e17'
down_revision = '743fd811f33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('title', sa.String(length=120), nullable=False))
    op.add_column('songs', sa.Column('title', sa.String(length=120), nullable=False))
    op.drop_column('songs', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('songs', 'title')
    op.drop_column('albums', 'title')
    # ### end Alembic commands ###
